#!/usr/bin/python3
from sys import argv

with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end='')

        # Check if the number is even
        if num % 2 == 0:
            print("{}*2".format(num // 2))
            continue

        # Check for odd factors
        for i in range(3, num, 2):
            if num % i == 0:
                factor = num // i
                
                # Check if the factor is prime (optional optimization)
                is_prime = True
                for j in range(3, int(factor ** 0.5) + 1, 2):
                    if factor % j == 0:
                        is_prime = False
                        break
                
                if is_prime:
                    print("{}*{}".format(factor, i))
                    break

